### ISSUE TITLE
Suas Monitor on Windows - build from Source

### ISSUE THREAD

**Issue by subzero10** [zendesk/Suas-Monitor#28]
The build from source documentation does not work for windows.

1. `npm start` does not set the NODE_ENV variable. On windows, you have to prefix with `set`, eg. `set NODE_ENV=production`.
2. After fixing this part of `npm start` command, we still have issues because we `electron` is not recognised as an executable (not registered in path). Looking at dependencies, Suas-Monitor uses `electron-prebuilt` which is deprecated.

Can you give us a more detailed guide on how to run Suas-Monitor on Windows?

**Comment by Kurounin** [comment]
I managed to make it run on Windows running these commands in the root folder:
```
.\node_modules\.bin\webpack.cmd
.\node_modules\.bin\electron.cmd .
```

**Comment by subzero10** [comment]
Awesome! Thanks!
